config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get "u/:utorid" => "public#profile", as: :profile
  resources :courses do
    resources :posts
  end

  resources :subscriptions
  resources :comments, only: [:create]

  post "post/vote" => "votes#create"

  root to: "public#index"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :courses, :through => :subscriptions
  has_many :posts
  has_many :comments
  has_many :votes

  validates_presence_of :first_name, :last_name, :utorid

  def full_name
    "#{first_name} #{last_name}"
  end 

  def liked_post_ids
    self.votes.where(like: true).pluck(:post_id)
  end
  
  def disliked_post_ids
    self.votes.where(like: false).pluck(:post_id)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :account

    validates_presence_of :message, :account_id, :post_id
end

app/models/course.rb
class Course < ApplicationRecord
    belongs_to :account
    validates_presence_of :name, :url, :rules
    has_many :posts
    has_many :subscriptions
    has_many :subscribers, :through => :subscriptions, :source => :account

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :account
    belongs_to :course
    validates_presence_of :title, :body, :account, :course_id 
    has_many :comments

    def score 
        if self.like > 0 || self.dislike > 0
            self.like > 0 ? (self.like - self.dislike) : (self.dislike * -1)
        else
            0
        end

    end
end 

app/models/subscription.rb
class Subscription < ApplicationRecord

    belongs_to :account
    belongs_to :course


end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :account
    belongs_to :post

    validates_uniqueness_of :account_id, scope: :post_id

    after_create :increment_vote
    after_destroy :decrement_vote

    private

    def increment_vote
        field = self.like ? :like : :dislike
        Post.find(self.post_id).increment(field).save
    end

    def decrement_vote
        field = self.like ? :like : :dislike
        Post.find(self.post_id).decrement(field ).save
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :utorid])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :utorid])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @comment = Comment.new comment_params
        @comment.account_id = current_account.id
        respond_to do |format|
            format.js{
                if @comment.save 
                    @comments = Comment.where(post_id: @comment.post_id)
                    render "comments/create"
                else
                    #unable to save
                end
            }
        end
    end


    def comment_params
        params.require(:comment).permit(:message, :post_id)
    end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    before_action :authenticate_account!, except: [ :index, :show ]
    before_action :set_course, only: [:show]

    def index
        @courses = Course.all
    end

    def show
        @posts = @course.posts.limit(20).sort_by{ |p| p.score}.reverse
        @subscriber_count = @course.subscribers.count

        @is_subscribed = account_signed_in? ? Subscription.where(course_id: @course.id, account_id: current_account.id).any? : false
        @subscription = Subscription.new
    end
 
    def create
        @course = Course.new course_values
        @course.account_id = current_account.id

        if @course.save
            redirect_to courses_path
        else
            render :new
        end
    end

    def new
        @course = Course.new
    end


    private

    def set_course
        @course = Course.find(params[:id])
    end
    
    def course_values
        params.require(:course).permit(:name, :url, :summary, :rules)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_account!, except: [ :index, :show ]
    before_action :set_post, only: [:show]
    before_action :auth_subscriber, only:[:new]

    def index
        @posts = Post.all
    end

    def show
        @comment = Comment.new
    end

    def new
        @course = Course.find(params[:course_id])
        @post = Post.new
    end


    def create
        @post = Post.new post_values
        @post.account_id = current_account.id
        @post.course_id = params[:course_id]

        if @post.save
            redirect_to course_path(@post.course_id)
        else
            @course = Course.find(params[:course_id])
            render :new
        end
    end

    private

    def set_post
        @post = Post.includes(:comments).find(params[:id])
    end
    
    def auth_subscriber
        unless Subscription.where(course_id: params[:course_id], account_id: current_account.id).any?
            redirect_to root_path, flash: { danger: "You must be signed in to view this page." }
        end
    end

    def post_values
        params.require(:post).permit(:title, :body)
    end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController

    def index
        @courses = Course.all.limit(5)
        @posts = Post.limit(20).sort_by{ |p| p.score}.reverse
    end

    def profile
        @profile = Account.find_by_utorid params[:utorid]
        @posts = @profile.posts
    end

end    

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

    def create
        @subscription = Subscription.new(subscription_params)
        @subscription.account_id = current_account.id
        @subscription.save
        redirect_to course_path(@subscription.course_id)
    end

    def subscription_params
        params.require(:subscription).permit(:course_id)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

    def create 
        post_id = params[:post_id]
        vote = Vote.new
        vote.post_id = params[:post_id]
        vote.like = params[:like]
        vote.account_id = current_account.id

        existing_vote = Vote.where(account_id: current_account.id, post_id: post_id)

        respond_to do |format|
            format.js{

                if existing_vote.size > 0
                    existing_vote.first.destroy
                else
                    if vote.save 
                        @success = true
                    else 
                        @success = false
                    end                
 
                end

                @post = Post.find(post_id)
                @is_like = params[:like]
                render "votes/create"

            }
        end
    end

    private

    def vote_params
        params.require(:vote).permit(:like, :post_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/votes_helper.rb
module VotesHelper
    def is_liked post
        account_signed_in? && current_account.liked_post_ids.include?(post.id) ? " active" : ""
    end

    def is_disliked post
        account_signed_in? && current_account.disliked_post_ids.include?(post.id) ? " active" : ""
    end
end

app/views/comments/create.js.erb
document.getElementById("#post-comments").innerHTML = "<%= escape_javascript(render partial: 'posts/comments', locals: { comments: @comments }) %>";

app/views/courses/_form.html.erb
<div class="row">
    <div class="col-sm-6">

        <%= form_for @course do |form| %>
            <div class="form-group">
                <%= label_tag :name%>
                <%= form.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= label_tag :url%>
                <%= form.text_field :url, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= label_tag :summary %>
                <%= form.text_field :summary, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= label_tag :rules %>
                <%= form.text_area :rules, class: "form-control" %>
            </div>
            <%= form.submit "Submit", class: "btn btn-primary" %>
        <% end %>

    </div>
</div>

app/views/courses/_subscribe.html.erb
<%= form_for @subscription do |f| %>
    <%= f.hidden_field :course_id, value: course_id%>
    <%= f.submit "Join Course", class: "btn btn-success float-right mt-3"%>
<% end %>

app/views/courses/index.html.erb
<div class="row">
    <div class="col-sm-12 mt-3">
        <% if account_signed_in? %>
            <div class="float-right mt-3">
                <%= link_to "Create New Course", new_course_path, class: "btn btn-outline-primary"%>
            </div>
        <% end %>
    </div>

    </div class="card">
        <div class="col">
            <% if @courses.size > 0 %>
                <% @courses.each do |course|%>
                        <h5><%= link_to course.name, course %></h5>
                        <p><%= simple_format course.summary %></p>
                <% end%>
            <% else %>
                <p> No courses to display. </p>
            <% end %>
        </div>
    </div>
</div>

app/views/courses/show.html.erb
<% if @is_subscribed %>
    <%= link_to "Create New Post", new_course_post_path(@course), class: "btn btn-primary float-right m-3"%>
<% else %>
    <%= render partial: "courses/subscribe", locals: { course_id: @course.id} %>
<% end %>

<h3 class="p-2 mt-3"><%= @course.name%></h3>

<div class="row">
    <div class="col-sm-8">
        <div class="">
            <div class="p-2">
                <%= render partial: "posts/list" , locals: { posts: @posts }%>
            </div>
        </div>
    </div>

    <div class="col-sm-4 float-right">
        <div class="card p-3">
            <h5> About this course </h5>
            <%= @course.summary %>
            <small>
                <p><h6>Course Page Rules</h4><%= simple_format @course.rules%></p> 
            </small>
            <p> <%= pluralize @subscriber_count, "member" %> </p>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
footer

app/views/layouts/_header.html.erb
<div class="container">
    <div class="row">
        <div class="col-12 pt-3 pb-3 border-bottom">
            <div class="float-right">
                <% if account_signed_in?%>
                    <div class="dropdown show">
                        <a class="btn btn-white dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <%= current_account.full_name %>
                        </a>

                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <%= link_to "Profile", profile_path(current_account.utorid), class: "dropdown-item" %>
                            <%= link_to "Settings", edit_account_registration_path, class: "dropdown-item" %>
                            <%= link_to "Log Out", destroy_account_session_path, method: "DELETE", class: "dropdown-item" %>
                        </div>
                    </div>
                <% else %>
                    <%= link_to "Log In", new_account_session_path, class: "btn btn-outline-primary" %>
                    <%= link_to "Sign Up", new_account_registration_path, class: "btn btn-primary"%>
                <% end %>
            </div>
            <p class="h3"> <%= link_to "Course Manager", root_path %> </p>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Course Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>    
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>  

    <section class="bg-light pb-4">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">   

            <%= yield %>

          </div>
        </div>
      </div>
    </section>

    <%# render partial: "layouts/footer" %>
  </body>
</html>

app/views/posts/_comments.html.erb
<% comments.each do |comment|%>
    <div class="post-comments">
        <%= link_to comment.account.full_name, profile_path(comment.account.utorid)%>
        <%= simple_format comment.message %>
    </div>
<% end %>

app/views/posts/_form.html.erb
<div class="row">
    <div class="col-sm-6">

        <%= form_for [@course, @post] do |form| %>
            <div class="form-group">
                <%= label_tag :title %>
                <%= form.text_field :title, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= label_tag :body %>
                <%= form.text_area :body, class: "form-control" %>
            </div>
            <%= form.submit "Submit", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/posts/_list.html.erb
<% @posts.each do |post| %>
    <div class="card p-3 mb-3"> 
        <div class="row ">
            <div class="col-1 text-center">
                <div id="vote-actions-<%= post.id %>" class="vote" data-id="<%= post.id %>">
                    <div class="fa fa-heart-o like <%= is_liked post %>" ></div>
                    <span class="score"><%= post.score %></span>
                    <div class="fa fa-thumbs-o-down dislike <%= is_disliked post %>"></div>
                </div>

            </div>

            <div class="col-11 col-md-10">
                <h4 class="mb-1"><%= link_to post.title, course_post_path(post.course_id , post) %></h4>

                <p> <small>
                    <%= link_to post.course.name, course_path(post.course)%>
                    Posted by <%= link_to post.account.full_name, profile_path(post.account.utorid)%> 
                    <%= time_ago_in_words post.created_at %> ago
                </small></p>

                <p><%= truncate post.body, length: 200 %>
                </p>
            </div>
        </div>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h2> Edit Post </h2>

<%= render partial: "form" %>

app/views/posts/new.html.erb
<h2> New Post </h2>

<%= render partial: "form" %>

app/views/posts/show.html.erb
<div class="row ">
    <div class="col-1 text-center">
        <div id="vote-actions-<%= @post.id %>" class="vote" data-id="<%= @post.id %>">
            <div class="fa fa-heart-o like <%= is_liked @post %>" ></div>
            <span class="score"><%= @post.score %></span>
            <div class="fa fa-thumbs-o-down dislike <%= is_disliked @post %>"></div>
        </div>
    </div>
    <div class="col-11 col-md-10">

        <h2 class="mt-3"><%= @post.title %> </h2>

        <%= simple_format @post.body %>

        <div id="comments">
            <%= render partial: "posts/comments", locals: { comments: @post.comments } %>
        </div>


        <h5>Leave a comment</h5>
        <%= form_for @comment, remote: true do |f| %>
            <%= f.hidden_field :post_id, value: @post.id %>
            <%= f.text_area :message, placeholder: "Comment goes here", class: "form-control" %>
            <%= f.submit "Submit comment", class: "btn btn-success mt-3"%>
        <% end %>
    </div>
</div>

app/views/votes/create.js.erb
//console.log("vote created");
$("#vote-actions-<%= @post.id %> .score").text("<%= @post.score %>")